#' Read a RaCInG simulation output file
#'
#' @param filename Path to a `.out` file generated by [runSim()].
#'
#' @return A list containing the average values, standard deviations, and raw counts.
#' @export
Read_Sim_Output <- function(filename) {

  # ------------------------------------------------------------
  # Purpose:
  #   Read simulation output (.out file) for any communication type
  #   (D, W, TT, CT, GSCC)
  #
  # The function parses:
  #   - Metadata
  #   - Raw counts (average + std)
  #   - Composition (average + std)
  #
  # Output format adapts automatically depending on type:
  #   D    → 2D (cell x cell)
  #   W/TT/CT → 3D (cell x cell x cell)
  #   GSCC → 1D (cell)
  # ------------------------------------------------------------

  # Read full file
  lines <- utils::read.csv(filename, header = FALSE, stringsAsFactors = FALSE)

  idx <- 1

  # -----------------------------
  # First line: communication type
  # -----------------------------
  triangle_type <- as.character(lines[idx, 1])
  idx <- idx + 1

  # -----------------------------
  # Second line: metadata
  # Format: cancer_type, weight_type, NoPat, N, itNo, av
  # -----------------------------
  meta <- lines[idx, ]
  idx <- idx + 1

  NoPat <- as.integer(meta[1])
  N <- as.integer(meta[2])
  itNo <- as.integer(meta[3])
  av <- as.numeric(meta[4])

  # -----------------------------
  # Determine dimensionality
  # -----------------------------
  if (triangle_type == "GSCC") {
    dim_type <- 1
  } else if (triangle_type == "D") {
    dim_type <- 2
  } else {
    dim_type <- 3
  }

  # Infer number of cells from the cellstring line (line 4). read.csv() pads
  # every row with NA up to the widest row in the file, so ncol() alone would
  # overcount whenever another line (e.g. the 4-field metadata line) is wider
  # than the cellstring line — count only the non-NA entries instead.
  nCells <- sum(!is.na(lines[4, ]))

  # -----------------------------
  # Initialize storage
  # -----------------------------
  if (dim_type == 3) {
    data_a <- array(0, dim = c(nCells, nCells, nCells, NoPat))
    data_s <- array(0, dim = c(nCells, nCells, nCells, NoPat))
  } else if (dim_type == 2) {
    data_a <- array(0, dim = c(nCells, nCells, NoPat))
    data_s <- array(0, dim = c(nCells, nCells, NoPat))
  } else {
    data_a <- array(0, dim = c(nCells, NoPat))
    data_s <- array(0, dim = c(nCells, NoPat))
  }

  raw_count <- matrix(0, nrow = NoPat, ncol = 2)
  block_size <- nCells^dim_type

  # -----------------------------
  # Read patient data
  # -----------------------------
  # Each composition block is read as one bulk slice + one vectorized matrix
  # assignment instead of one lines[idx,] subset per row -- for W/TT/CT
  # (block_size = nCells^3, ~18.4 million at 264 cell types) the per-row
  # version takes minutes per patient; this takes a fraction of a second.
  while (idx <= nrow(lines)) {

    p <- as.integer(lines[idx, 1]) # patient ID, the other columns correspond to N and avg
    idx <- idx + 1

    if (is.na(p)) break

    # Skip cell names line
    idx <- idx + 1

    # Raw count
    vals <- lines[idx, ]
    idx <- idx + 1

    raw_count[p, 1] <- as.numeric(vals[2])  # average
    raw_count[p, 2] <- as.numeric(vals[3])  # std

    # Skip "Composition - Average"
    idx <- idx + 1

    avg_block <- as.matrix(lines[idx:(idx + block_size - 1), seq_len(dim_type + 1), drop = FALSE])
    mode(avg_block) <- "numeric"
    idx <- idx + block_size

    # Skip "Composition - Std"
    idx <- idx + 1

    std_block <- as.matrix(lines[idx:(idx + block_size - 1), seq_len(dim_type + 1), drop = FALSE])
    mode(std_block) <- "numeric"
    idx <- idx + block_size

    if (dim_type == 3) {
      data_a[cbind(avg_block[, 1], avg_block[, 2], avg_block[, 3], p)] <- avg_block[, 4]
      data_s[cbind(std_block[, 1], std_block[, 2], std_block[, 3], p)] <- std_block[, 4]
    } else if (dim_type == 2) {
      data_a[cbind(avg_block[, 1], avg_block[, 2], p)] <- avg_block[, 3]
      data_s[cbind(std_block[, 1], std_block[, 2], p)] <- std_block[, 3]
    } else {
      data_a[cbind(avg_block[, 1], p)] <- avg_block[, 2]
      data_s[cbind(std_block[, 1], p)] <- std_block[, 2]
    }
  }

  # -----------------------------
  # Return output
  # -----------------------------
  return(list(
    data_avg = data_a,
    data_std = data_s,
    raw_count = raw_count
  ))
}

# compute_results_processing <- function(celltypes,
#                                        patient_names,
#                                        triangle_type,      ### CHECK WHETHER WE NEED TO CONSIDER DIFFERENT TYPES OF TRIANGLE!!
#                                        remove_direction = TRUE,
#                                        normalized = TRUE,
#                                        sim_raw_file = NULL, sim_norm_file = NULL,
#                                        output_folder = NULL, file.name = NULL) {

#   # -----------------------------
#   nCells <- length(celltypes)  # number of cell types

#   # -----------------------------
#   # Read simulation outputs
#   # -----------------------------
#   # data_raw  : non-normalized simulation
#   # data_norm : normalized (uniform) simulation
#   data_raw  <- Read_Sim_Output(sim_raw_file)
#   if (normalized) data_norm <- Read_Sim_Output(sim_norm_file)

#   # Extract arrays of averages and patient-level raw counts
#   av      <- data_raw$data_avg
#   summary <- data_raw$raw_count
#   if (normalized) {
#     avN     <- data_norm$data_avg
#     summaryN <- data_norm$raw_count
#   } else {
#     avN <- NULL
#     summaryN <- NULL
#   }

#   # -----------------------------
#   # Convert arrays → data frames
#   # -----------------------------
#   # This step converts multi-dimensional arrays (triangle, direct, or GSCC) into
#   # data frames where each column corresponds to a labeled combination of cell types.
#   non_unif_data <- list()
#   unif_data     <- list()

#   if (length(dim(av)) == 4) {  # Triangles (3D interactions) + patients
#     for (i in 1:nCells) {
#       for (j in 1:nCells) {
#         for (k in 1:nCells) {
#           label <- paste(celltypes[i], celltypes[j], celltypes[k], sep = "_")
#           non_unif_data[[label]] <- av[i, j, k, ]
#           if (normalized) unif_data[[label]] <- avN[i, j, k, ]
#         }
#       }
#     }
#   } else if (length(dim(av)) == 3) {  # Direct interactions (2D) + patients
#     for (i in 1:nCells) {
#       for (j in 1:nCells) {
#         label <- paste(celltypes[i], celltypes[j], sep = "_")
#         non_unif_data[[label]] <- av[i, j, ]
#         if (normalized) unif_data[[label]] <- avN[i, j, ]
#       }
#     }
#   } else {  # GSCC (1D) + patients
#     for (i in 1:nCells) {
#       label <- celltypes[i]
#       non_unif_data[[label]] <- av[i, ]
#       if (normalized) unif_data[[label]] <- avN[i, ]
#     }
#   }

#   # Convert lists to data frames for easier manipulation
#   df  <- as.data.frame(non_unif_data)
#   dfN <- if (normalized) as.data.frame(unif_data) else NULL

#   # -----------------------------
#   # Remove direction (merge labels)
#   # -----------------------------
#   # Some triangle types (like W) are directional; this step merges counts for
#   # interactions that are equivalent when ignoring direction.
#   if (remove_direction) {
#     new  <- data.frame(matrix(nrow = nrow(df), ncol = 0))
#     newN <- if (normalized) data.frame(matrix(nrow = nrow(df), ncol = 0)) else NULL

#     for (colname in colnames(df)) {
#       parts <- strsplit(colname, "_")[[1]]

#       if (triangle_type == "W" && length(parts) == 3) {
#         # Sort only first and last cell for W triangles
#         sorted_parts <- sort(c(parts[1], parts[3]))
#         parts[1] <- sorted_parts[1]
#         parts[3] <- sorted_parts[2]
#         new_label <- paste(parts, collapse = "_")
#       } else {
#         # Sort all parts for other types (fully direction-agnostic)
#         new_label <- paste(sort(parts), collapse = "_")
#       }

#       # Accumulate counts for merged labels
#       if (new_label %in% colnames(new)) {
#         new[[new_label]] <- new[[new_label]] + df[[colname]]
#         if (normalized) newN[[new_label]] <- newN[[new_label]] + dfN[[colname]]
#       } else {
#         new[[new_label]] <- df[[colname]]
#         if (normalized) newN[[new_label]] <- dfN[[colname]]
#       }
#     }

#     # Update arrays for normalization
#     av  <- as.matrix(new)
#     if (normalized) avN <- as.matrix(newN)
#   }

#   # -----------------------------
#   # Normalization
#   # -----------------------------
#   # Perform normalization only when requested. If not normalizing, use raw counts.
#   if (normalized) {
#     # Replace zero baseline counts to avoid division by zero.
#     zero_idx <- which(av == 0 & avN == 0, arr.ind = TRUE)
#     if (nrow(zero_idx) > 0) {
#       av[zero_idx]  <- 1
#       avN[zero_idx] <- 1
#     }

#     # Replace any remaining zeros in baseline to 1 (to prevent division errors)
#     avN[avN == 0] <- 1

#     # Normalize counts: divide non-uniform by uniform counts
#     Norm <- av / avN
#   } else {
#     # Skip normalization and use raw counts
#     Norm <- av
#   }

#   # -----------------------------
#   # Remove patients where simulation failed
#   # -----------------------------
#   # Patients with zero total counts in raw or baseline simulations are excluded
#   # because they indicate failed or empty simulations.
#   if (normalized && !is.null(summaryN)) {
#     delete_indices <- unique(c(which(summary[,1] == 0), which(summaryN[,1] == 0)))
#   } else {
#     delete_indices <- which(summary[,1] == 0)
#   }

#   if (length(delete_indices) > 0) {
#     Norm <- Norm[-delete_indices, , drop = FALSE]
#     patients <- patient_names[-delete_indices]
#   } else {
#     patients <- patient_names
#   }

#   # -----------------------------
#   # Convert normalized data to dataframe
#   # -----------------------------
#   df <- as.data.frame(Norm)
#   rownames(df) <- patients

#   # -----------------------------
#   # Save CSV
#   # -----------------------------
#   write.csv(df, file = file.path(output_folder, file.name), row.names = TRUE)

#   return(df)
# }

#' Convert raw simulation outputs into feature matrices
#'
#' @param celltypes Character vector of cell-type names.
#' @param patient_names Character vector of patient identifiers.
#' @param triangle_type Communication type (`"D"`, `"W"`, `"TT"`, `"CT"`, or `"GSCC"`).
#' @param remove_direction Logical; if `TRUE`, merge directionally equivalent features.
#' @param normalized Logical; if `TRUE`, divide raw values by a uniform baseline.
#' @param sim_raw_file Path to the raw simulation output file.
#' @param sim_norm_file Optional path to the normalized simulation output file.
#' @param output_folder Directory where the processed CSV files are written.
#' @param file.name Output filename stem.
#'
#' @return A list with processed mean and standard-deviation data frames.
#' @export
compute_results_processing <- function(celltypes,
                                       patient_names,
                                       triangle_type,
                                       remove_direction = TRUE,
                                       normalized = TRUE,
                                       sim_raw_file = NULL, sim_norm_file = NULL,
                                       output_folder = NULL, file.name = NULL) {

  # -----------------------------
  nCells <- length(celltypes)  # number of cell types

  # -----------------------------
  # Read simulation outputs
  # -----------------------------
  # data_raw  : non-normalized simulation
  # data_norm : normalized (uniform) simulation
  data_raw  <- Read_Sim_Output(sim_raw_file)
  if (normalized) data_norm <- Read_Sim_Output(sim_norm_file)

  # Extract arrays of averages and patient-level raw counts and stds
  av      <- data_raw$data_avg
  av_sd   <- data_raw$data_std
  summary <- data_raw$raw_count
  if (normalized) {
    avN     <- data_norm$data_avg
    avN_sd  <- data_norm$data_std
    summaryN <- data_norm$raw_count
  } else {
    avN <- NULL
    avN_sd <- NULL
    summaryN <- NULL
  }

  # -----------------------------
  # Convert arrays -> labeled [patient x interaction] matrices directly via a
  # single reshape instead of building one named-list entry per interaction
  # then converting to a data.frame -- for Triangles (nCells^3 interactions,
  # ~18.4 million at 264 cell types) the list/data.frame version takes
  # minutes; a reshape is instantaneous regardless of nCells.
  #
  # Labels are plain cell-type combinations here (no type prefix) so the
  # remove_direction merging below keeps working unchanged; the "Dir_"/"W_"/
  # etc. prefix that makes these columns match compute_racing_kernel()'s
  # feature names is added once, at the very end, after bundling/normalization.
  .array_to_labeled_matrix <- function(arr, celltypes) {
    d <- dim(arr)
    dim_type <- length(d) - 1
    nCells <- d[1]
    NoPat <- d[length(d)]
    out <- t(matrix(arr, nrow = nCells^dim_type, ncol = NoPat))
    if (dim_type == 1) {
      labels <- celltypes
    } else {
      grid <- do.call(expand.grid, rep(list(seq_len(nCells)), dim_type))
      labels <- do.call(paste, c(lapply(grid, function(idx) celltypes[idx]), list(sep = "_")))
    }
    colnames(out) <- labels
    out
  }

  # The index grid driving column order in .array_to_labeled_matrix() above
  # (needed again below to group columns for remove_direction by *index*,
  # not by parsing back the pasted labels -- cell-type names can themselves
  # contain "_", e.g. multideconv's method-tagged names like
  # "CBSX_CBSX.HNSCC.scRNAseq_B.cells", so splitting a label such as
  # "A_B_CBSX_CBSX.HNSCC.scRNAseq_B.cells" on "_" cannot tell which
  # underscores separate cell types from underscores inside one cell-type's
  # own name -- silently scrambling which columns get merged together).
  dim_type <- length(dim(av)) - 1
  index_grid <- if (dim_type > 1) do.call(expand.grid, rep(list(seq_len(nCells)), dim_type)) else NULL

  av    <- .array_to_labeled_matrix(av, celltypes)
  av_sd <- .array_to_labeled_matrix(av_sd, celltypes)
  if (normalized) {
    avN    <- .array_to_labeled_matrix(avN, celltypes)
    avN_sd <- .array_to_labeled_matrix(avN_sd, celltypes)
  }

  # -----------------------------
  # Remove direction (merge labels)
  # -----------------------------
  # Some triangle types (like W) are directional; this step merges counts for
  # interactions that are equivalent when ignoring direction. Grouping is
  # computed from index_grid's integer columns (never ambiguous, unlike
  # re-splitting the pasted string labels -- see note above), then rowsum()
  # (a single vectorized grouped-sum) does the actual merge, replacing what
  # was previously the same nCells^3-scale bottleneck as above.
  if (remove_direction && dim_type > 1) {
    new_labels <- vapply(seq_len(nrow(index_grid)), function(r) {
      idx <- as.integer(index_grid[r, ])
      if (triangle_type == "W" && length(idx) == 3) {
        # Sort only first and last cell for W triangles
        sorted_idx <- sort(c(idx[1], idx[3]))
        paste(sorted_idx[1], idx[2], sorted_idx[2], sep = "_")
      } else {
        # Sort all indices for other types (fully direction-agnostic)
        paste(sort(idx), collapse = "_")
      }
    }, character(1))

    av <- t(rowsum(t(av), group = new_labels))
    if (normalized) avN <- t(rowsum(t(avN), group = new_labels))
    # merge variances (sum variances when summing counts), then convert back to sd
    av_sd <- sqrt(t(rowsum(t(av_sd^2), group = new_labels)))
    if (normalized) avN_sd <- sqrt(t(rowsum(t(avN_sd^2), group = new_labels)))

    # rowsum() leaves the index-based group keys (e.g. "1_2_3") as column
    # names; convert back to real cell-type-name labels now that grouping is
    # done -- safe to split on "_" here since these keys are our own
    # small-integer strings, never real (possibly "_"-containing) cell-type names.
    .relabel_from_index_keys <- function(mat) {
      idx_keys <- strsplit(colnames(mat), "_")
      colnames(mat) <- vapply(idx_keys, function(idx) {
        paste(celltypes[as.integer(idx)], collapse = "_")
      }, character(1))
      mat
    }
    av    <- .relabel_from_index_keys(av)
    av_sd <- .relabel_from_index_keys(av_sd)
    if (normalized) {
      avN    <- .relabel_from_index_keys(avN)
      avN_sd <- .relabel_from_index_keys(avN_sd)
    }
  }

  # -----------------------------
  # Normalization
  # -----------------------------
  # Perform normalization only when requested. If not normalizing, use raw counts.
  if (normalized) {
    # Replace zero baseline counts to avoid division by zero.
    zero_idx <- which(av == 0 & avN == 0, arr.ind = TRUE)
    if (nrow(zero_idx) > 0) {
      av[zero_idx]  <- 1
      avN[zero_idx] <- 1
      # corresponding sds -> set to 0 (no uncertainty on forced 1)
      if (!is.null(av_sd))  av_sd[zero_idx]  <- 0
      if (!is.null(avN_sd)) avN_sd[zero_idx] <- 0
    }

    # Replace any remaining zeros in baseline to 1 (to prevent division errors)
    avN_zero_before <- avN == 0
    avN[avN == 0] <- 1
    if (!is.null(avN_sd)) avN_sd[avN_zero_before] <- 0

    # Normalize counts: divide non-uniform by uniform counts
    Norm_mean <- av / avN

    # propagate sd using delta method (assumes independence)
    av_var  <- (av_sd)^2
    avN_var <- (avN_sd)^2
    # guard if sd matrices are NULL (shouldn't be, but safe)
    if (is.null(av_sd))  av_var <- matrix(0, nrow = nrow(av), ncol = ncol(av))
    if (is.null(avN_sd)) avN_var <- matrix(0, nrow = nrow(avN), ncol = ncol(avN))
    # Var(X/Y) ≈ Var(X)/μY^2 + μX^2 * Var(Y) / μY^4
    Norm_var <- (av_var / (avN^2)) + ((av^2) * avN_var / (avN^4))
    Norm_sd  <- sqrt(Norm_var)
  } else {
    # Skip normalization and use raw counts
    Norm_mean <- av
    Norm_sd   <- av_sd
  }

  # -----------------------------
  # Remove patients where simulation failed
  # -----------------------------
  # Patients with zero total counts in raw or baseline simulations are excluded
  # because they indicate failed or empty simulations.
  if (normalized && !is.null(summaryN)) {
    delete_indices <- unique(c(which(summary[,1] == 0), which(summaryN[,1] == 0)))
  } else {
    delete_indices <- which(summary[,1] == 0)
  }

  if (length(delete_indices) > 0) {
    Norm_mean <- Norm_mean[-delete_indices, , drop = FALSE]
    Norm_sd   <- Norm_sd[-delete_indices, , drop = FALSE]
    patients <- patient_names[-delete_indices]
  } else {
    patients <- patient_names
  }

  # -----------------------------
  # Convert normalized data to dataframe (means + sd)
  # -----------------------------
  # Prefix columns to match compute_racing_kernel()'s feature naming exactly
  # ("Dir_A_B", "W_A_B_C", "TT_A_B_C", "CT_A_B_C", "GSCC_A") so kernel- and
  # Monte-Carlo-derived feature matrices use identical column names for the
  # same cell-type combination and can be fed into the same downstream
  # statistical/plotting functions interchangeably.
  feature_prefix <- if (triangle_type == "D") "Dir" else triangle_type
  colnames(Norm_mean) <- paste0(feature_prefix, "_", colnames(Norm_mean))
  colnames(Norm_sd)   <- paste0(feature_prefix, "_", colnames(Norm_sd))

  df_mean <- as.data.frame(Norm_mean)
  rownames(df_mean) <- patients
  df_sd_out <- as.data.frame(Norm_sd)
  rownames(df_sd_out) <- patients

  # -----------------------------
  # Save CSVs
  # -----------------------------
  utils::write.csv(df_mean, file = file.path(output_folder, file.name), row.names = TRUE)
  utils::write.csv(df_sd_out, file = file.path(output_folder, paste0(file.name, "_sd.csv")), row.names = TRUE)

  return(list(mean = df_mean, sd = df_sd_out))
}